sudo: required
addons:
  chrome: stable

language: node_js
cache:
  bundler: true
  directories:
  - node_modules # NPM packages

node_js:
   - node

branches:
   only:
      - master # will only build for master branch commits

before_script:
   - npm install -g --silent firebase-tools # installs firebase to run firebase deploy
   - npm install -g --silent @angular/cli

script:
   - ng test
   - ng lint
   - ./src/scripts/deploy-script.sh
   - ng build --prod

deploy:
    provider: firebase
    token:
        secure: $FIREBASE_TOKEN
