language: node_js
cache:
  bundler: true
  directories:
  - node_modules # NPM packages

node_js:
   - node

branches:
   only:
      - master # will only build for master branch commits

before_script:
   - npm install -g --silent firebase-tools # installs firebase to run firebase deploy
   - npm install -g --silent @angular/cli

script:
   - ./src/scripts/deploy-script.sh
   - ng lint
   - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive # firebase deploy after angular-cli build
